In [ ]:
#     Name- Deepak Yadav  PRN- 22070521023
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
#     Name- Deepak Yadav  PRN- 22070521023
df=pd.read_csv("D:/Python_nb/iris.csv")

In [3]:
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [ ]:
#     Name- Deepak Yadav  PRN- 22070521023
x=df.iloc[:,:-1].values
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
#    Name- Deepak Yadav  PRN- 22070521023
y=df.iloc[:,4].values
y

array(['Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolo

In [6]:
#     NAME- Tarun Kumar Singh     PRN- 22070521014
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
# scaler.fit(x_train)
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [7]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [8]:
KNeighborsClassifier()

KNeighborsClassifier()

In [9]:
x_test

array([[-0.06757179,  2.14392331, -1.38710027, -1.25517775],
       [-0.42012028, -1.86487921,  0.16026258,  0.15850367],
       [ 0.52000902,  0.49323992,  0.54710329,  0.54405315],
       [ 0.16746053, -0.92163156,  0.76815513,  0.54405315],
       [ 0.52000902, -0.92163156,  0.65762921,  0.80108614],
       [ 0.52000902, -0.68581965,  0.76815513,  0.41553666],
       [-0.53763645,  0.72905183, -1.11078547, -1.25517775],
       [-1.47776575,  0.257428  , -1.27657435, -1.25517775],
       [ 0.40249286, -0.68581965,  0.60236625,  0.80108614],
       [ 0.16746053, -0.45000773,  0.43657738,  0.41553666],
       [-0.06757179, -0.68581965,  0.76815513,  1.5721851 ],
       [-1.0077011 ,  0.96486374, -1.16604843, -0.74111178],
       [-1.12521726, -1.6290673 , -0.22657813, -0.2270458 ],
       [-0.06757179, -1.15744347,  0.16026258,  0.02998718],
       [-1.12521726, -1.39325539,  0.43657738,  0.67256965],
       [ 0.16746053, -2.10069112,  0.71289217,  0.41553666],
       [-0.89018493,  0.

In [10]:
y_pred=classifier.predict(x_test)
y_pred

array(['Setosa', 'Versicolor', 'Versicolor', 'Virginica', 'Virginica',
       'Versicolor', 'Setosa', 'Setosa', 'Virginica', 'Versicolor',
       'Virginica', 'Setosa', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Setosa', 'Virginica', 'Versicolor', 'Versicolor',
       'Virginica', 'Versicolor', 'Setosa', 'Virginica', 'Versicolor',
       'Setosa', 'Virginica', 'Versicolor', 'Virginica', 'Virginica'],
      dtype=object)

In [ ]:
#    Name- Deepak Yadav  PRN- 22070521023
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[ 7  0  0]
 [ 0 10  2]
 [ 0  3  8]]


In [12]:
y_pred=classifier.predict([[ 0.31267862, -0.63054767,  0.49240039,  0.68775489]])
y_pred

array(['Versicolor'], dtype=object)